from pydantic import BaseModel, Field, HttpUrl
from typing import List, Dict, Any, Optional, Union
from enum import Enum
import datetime
from dataclasses_json import dataclass_json

class MessageRole(str, Enum):
    """Enum for message roles"""
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    FUNCTION = "function"

@dataclass_json
class MessageSchema(BaseModel):
    """Schema for chat messages (OpenAI compatible)"""
    role: MessageRole
    content: str
    name: Optional[str] = None
    function_call: Optional[Dict[str, Any]] = None
    
    class Config:
        use_enum_values = True

class BuildIndexRequest(BaseModel):
    """Schema for build_index endpoint request"""
    urls: List[HttpUrl] = Field(..., description="List of URLs to crawl and index")

class BuildIndexResponse(BaseModel):
    """Schema for build_index endpoint response"""
    status: str = Field(..., description="Status of the indexing operation")
    processed_urls: Optional[int] = Field(None, description="Number of URLs successfully processed")
    errors: Optional[Dict[str, str]] = Field(None, description="Errors encountered during processing")
    message: Optional[str] = Field(None, description="Additional information")

class FunctionCall(BaseModel):
    """Schema for function calls"""
    name: str = Field(..., description="Name of the function to call")
    arguments: str = Field(..., description="Arguments for the function call in JSON string format")

class FunctionCallObject(BaseModel):
    """Schema for function call objects"""
    id: Optional[str] = Field(None, description="Unique identifier for this tool call")
    type: str = Field("function", description="Type of tool call")
    function: FunctionCall

class FunctionDefinition(BaseModel):
    """Schema for function definitions"""
    name: str = Field(..., description="Name of the function")
    description: Optional[str] = Field(None, description="Description of what the function does")
    parameters: Dict[str, Any] = Field(..., description="Parameters the function accepts")

class FunctionTool(BaseModel):
    """Schema for function tools"""
    type: str = Field("function", description="Type of the tool")
    function: FunctionDefinition

class ChatRequest(BaseModel):
    """Schema for chat endpoint request (OpenAI compatible)"""
    messages: List[MessageSchema] = Field(..., description="List of messages in the conversation")
    model: Optional[str] = Field(None, description="Model to use for generation")
    temperature: Optional[float] = Field(None, description="Sampling temperature")
    max_tokens: Optional[int] = Field(None, description="Maximum number of tokens to generate")
    tools: Optional[List[FunctionTool]] = Field(None, description="List of tools available to the model")
    tool_choice: Optional[Union[str, Dict[str, Any]]] = Field(None, description="Which tool to use")
    stream: Optional[bool] = Field(False, description="Whether to stream the response")
    
    class Config:
        use_enum_values = True

class ChatResponseChoice(BaseModel):
    """Schema for chat response choice (OpenAI compatible)"""
    index: int = Field(0, description="Index of the choice")
    message: MessageSchema = Field(..., description="The message generated by the model")
    finish_reason: Optional[str] = Field(None, description="Reason why the model stopped generating")

class Usage(BaseModel):
    """Schema for token usage information (OpenAI compatible)"""
    prompt_tokens: int = Field(..., description="Number of tokens in the prompt")
    completion_tokens: int = Field(..., description="Number of tokens in the completion")
    total_tokens: int = Field(..., description="Total number of tokens used")

class ChatResponse(BaseModel):
    """Schema for chat endpoint response (OpenAI compatible)"""
    id: str = Field(..., description="Unique identifier for the response")
    object: str = Field("chat.completion", description="Object type")
    created: int = Field(..., description="Unix timestamp of the creation time")
    model: str = Field(..., description="Model used for generation")
    choices: List[ChatResponseChoice] = Field(..., description="List of completion choices")
    usage: Usage = Field(..., description="Token usage information")